### ISSUE TITLE
Add to README the GitHub Action for this library

### ISSUE THREAD

**Issue by emibcn** [bokub/gradient-badge#1]
Hello!!

I just created a GitHub Action that interfaces with this project for creating a badge during a workflow. You can check it at https://github.com/emibcn/badge-action

Maybe you want to add this to your README so anyone can use your tool on their workflows?

**Comment by bokub** [comment]
That's such a great idea ! I'll add it today

BTW, did you manage to use the generated artifacts in a README ? I don't see any example in your repo's README

**Comment by emibcn** [comment]
I posted an [answer in StackOverflow](https://stackoverflow.com/a/63765701/2928168) explaining how to save the asset into the repo. In the [action workflow](https://github.com/emibcn/badge-action/blob/7c9e02c01bcc2eec3948b37e49f1f7551370361b/.github/workflows/test.yml#L25), it only saves the SVG as a GitHub artifact, which only can be downloaded as a ZIP file containing it, so it cannot be added to the README.

Maybe I'm going to apply the StackOverflow answer to myself and save the generated file into the repo, so it can be added to the README ;)

**Comment by bokub** [comment]
My suggestion would be to commit the badges in a dedicated orphan branch (named `badges` for example), so you avoid unwanted commits in your main branch, and you can still link them in your README

**Comment by emibcn** [comment]
Just done the other solution: https://github.com/emibcn/badge-action/blob/88b8f35d4c9fbd776e921f3eea831d4fdb8d4387/.github/workflows/test.yml

But I like yours even more: Save the badges into `badge` branch, into `${{ branch }}` directory.

**Comment by emibcn** [comment]
Well, just did it ;P

https://github.com/emibcn/badge-action/blob/850d7863d3685b1c4b7033535f1b3a75d0f25534/.github/workflows/test.yml

**Comment by bokub** [comment]
I've added a line to the README !
