### ISSUE TITLE
Missing file `colors.js` in NPM package

### ISSUE THREAD

**Issue by emibcn** [bokub/gradient-badge#2]
Hello!!

I'm using this library on an [action](https://github.com/emibcn/badge-action), but there is a missing file in the package distributed by NPM. I'm using version `1.3.0` of `gradient-badge`. As the action is delivered via `ncc` compiled file `dist/index.js`, I could hack it by copying your repo's [`colors.js`](https://github.com/bokub/gradient-badge/blob/master/colors.js) to `node-modules/gradient-badge/colors.js`. Then I could pack it and successfully execute it.

**Comment by bokub** [comment]
It's my mistake, I forgot to include it in the npm `files`, but I just fixed it in version `1.3.1`

Please do no use the `dist` folder, it's made for browsers. Instead, use `index.js` and `colors.js`

([File structure](https://cdn.jsdelivr.net/npm/gradient-badge@1.3.1/))

**Comment by emibcn** [comment]
> Please do no use the `dist` folder, it's made for browsers. Instead, use `index.js` and `colors.js`

Of course not. I use dist for packaged folder on _my_ project (with all deps), not for including yours.
